### ISSUE TITLE
Querying embedded documents and clojure maps

### ISSUE THREAD

**Issue by CharlesHD** [michaelklishin/monger#178]
According to MongoDB [documentation](https://docs.mongodb.com/manual/tutorial/query-embedded-documents/), there is a difference in using bracket and dot notation for querying embedded documents. 

This means that 
`db.inventory.find( { size: { h: 14, w: 21 } } )`
and 
`db.inventory.find( { size: { w: 21, h: 14 } } )`
 do not return same results. 

This is particularly awful since clojure maps are unordered. The behavior of 
`(mc/find db "inventory" {:size {:h 14 :w 21}})` may be unspecified. 

Correct way to handle this is to use the mongodb dot notation : 
`db.inventory.find( { "size.h": 14, "size.w": 21 } )`. 

Since in many clojure map types, order is unspecified, I wish `monger.conversion/to-db-object` convert nested maps using dot notation.

**Comment by michaelklishin** [comment]
This has been brought up before and Monger docs [mention this and similar topics](http://clojuremongodb.info/articles/querying.html) of map ordering and what it means semantically in MongoDB queries.

Array maps are ordered. Use them. I find the whole reliance on field order to be a deficiency in the MongoDB query syntax. I don't think Monger should mess with the inputs: it's been a library that is very close in spirit to the MongoDB shell since day 1 (for over 7 years now).
