### ISSUE TITLE
While authenticating, "connect-via-uri" does not take uri.authSource into consideration.

### ISSUE THREAD

**Issue by tawus** [michaelklishin/monger#96]
Here is a workaround (the key is to use MongoClientURI.getCredentials)

```clojure
(defn connect-via-uri                                                                                                                                                                 
  [uri-string]                                                                                                                                                                        
  (let [uri  (MongoClientURI. uri-string)                                                                                                                                             
        source (.getSource (.getCredentials uri))                                                                                                                                     
        conn (MongoClient. uri)                                                                                                                                                       
        db   (.getDB conn (.getDatabase uri))                                                                                                                                         
        source-db (if (= (.getDatabase uri) source)                                                                                                                                   
                    db                                                                                                                                                                
                    (.getDB conn source))                                                                                                                                             
        user (.getUsername uri)                                                                                                                                                       
        pwd  (.getPassword uri)]                                                                                                                                                      
    (when (and user pwd)                                                                                                                                                              
      (when-not (mg/authenticate source-db user pwd)                                                                                                                                  
        (throw (IllegalArgumentException.                                                                                                                                             
                (str "Could not authenticate with MongoDB. "                                                                                                                          
                     "Either database name or credentials are invalid."                                                                                                               
                     (format "Database name: %s, username: %s" (.getName source-db) user))))))                                                                                        
    {:conn conn :db db}))
```

**Comment by michaelklishin** [comment]
@tawus please submit a PR with a test.

**Comment by theHeimes** [comment]
Maybe my authentication issue is caused by this:
Authentication against a DB2 database instance running wire-listener protocol fails with monger.
Monger does not authenticate with
(let [uri "127.0.0.1"
      conn (mg/connect uri)
      db (mg/get-db conn "myjson")
      u "me"
      p (.toCharArray "$omePa55W0Rd")]
  (mg/authenticate db u p))

p.s. connecting with the mongo-shell [mongo --host 127.0.0.1 -u me -p $omePa55W0Rd] and python works, so I assume the basic setup is ok.

**Comment by theHeimes** [comment]
Hi Michael,
Sorry for raising this topic, but while investigating this issue further, I found out that this is a problem caused by IBM's implementation of their wrapper for MongoDB. 
Appreciate your work.
Best regards

**Comment by lkrubner** [comment]
Did this make it into the 2.0.1 release? I am trying to run an app on a new AWS instance. No matter what I do I get: 

    java.lang.IllegalArgumentException: Could not authenticate with MongoDB. Either database name or credentials are invalid. 

If I:

    emacs /etc/mongod.conf

and: 

# Turn on/off security.  Off is currently the default                                                                                                               
#noauth=true                                                                                                                                                        
auth=true

or: 

    # Turn on/off security.  Off is currently the default                                                                                                               
    noauth=true                                                                                                                                                        
    #auth=true

and: 

    service mongod restart

I still get the same error. 

Also, if I print the connection uri to the terminal, and then copy and paste the database, username, and password to another terminal, logging into the mongo shell, everything works perfectly. So using that database, username and password works via the mongo shell. Just not via the connection URI. 

I edited the security group on AWS to open up the port 27017. 

I can not think of what else the problem is.

**Comment by michaelklishin** [comment]
This issue isn't resolved. It is also probably not relevant in master, which uses the new MongoDB Java client. So try master first.

When in doubt, check MongoDB logs (ideally with verbose logging).

**Comment by michaelklishin** [comment]
I don't think this is relevant for 3.0 RCs, please leave a note if I'm wrong.
